### ISSUE TITLE
i

### ISSUE THREAD

**Issue by BeanieMen** [BeanieMen/ubiquibot#2]

**Comment by BeanieMen** [comment]
man everythings enabled
```
command-settings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true
```
